### ISSUE TITLE
Where do you get openapi.json for different specified version

### ISSUE THREAD

**Issue by zhuqw12** [heromicro/slurmrestapi.go#1]
Hi, I am using openapi generator to generate structs code too. I find that the full version of file "openapi.json" can get from slurmrestd interface http://<slurmrestdhost:slurmrestdip>/openapi.json. But here, you got 3 specified version of openapi.json for different branches. So can I ask you where did you get these versioned "openapi.json"?

**Comment by heromicro** [comment]
Deploy a slurm cluster, and slurmrestd, the slurmrestd service start with specific args `-s openapi/v0.0.39,openapi/dbv0.0.39` , if you need v0.0.39, or ` -s openapi/v0.0.38,openapi/dbv0.0.38` if you need v0.0.38.

Then, use curl to get the versioned openapi.json.
